on: workflow_call
jobs:
  phpcs:
    name: Run PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: tokenizer, xmlwriter, simplexml
          tools: ${{ github.event_name == 'pull_request' && 'cs2pr' || '' }}
          coverage: none
      - name: Install dependencies
        run: |
          composer update --no-interaction      
      - name: Run PHP Code Sniffer
        run: ./vendor/bin/phpcs -q --standard=./phpcs.xml src ${{ github.event_name == 'pull_request' && '| cs2pr' || '' }}
