on: workflow_call
jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: tokenizer, xmlwriter, simplexml
          tools: ${{ github.event_name == 'pull_request' && 'cs2pr' || '' }}
          coverage: none
      - name: Install dependencies
        run: |
          composer update --no-interaction      
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --configuration=./phpstan.neon --error-format=checkstyle src | cs2pr
